language: node_js
node_js: node
cache: npm

branches:
  only:
    - development

install:
  - npm install

script:
  - npm run lint

deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    branch: development
