name: CD

on:
  release:
    types:
      - created

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm run deploy
        with:
          env:
            TRAVIS_REPO_SLUG: ascoderu/ascoderu.github.io
            GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
