name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: bahmutov/npm-install@v1
      - run: npm run lint
